### ISSUE TITLE
mysql, spring 연동

### ISSUE THREAD

**Issue by hades2015** [hades2015/koreatech-ev#1]

**Comment by changhoon-kim** [comment]
연동 완료

**Comment by hades2015** [comment]
디비 서버 변경으로 인해 다시 염

**Comment by hades2015** [comment]
연동 완료 
서버에서 /etc/mysql/my.conf 의 bind-address 0.0.0.0 으로 변경(0.0.0.0 은 anywhere)
mysql  재시동(service mysql restart 또는 /etc/init.d/mysql restart)
root 에게 모든 권한 부여

``` SQL
GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION
```

<a href="http://javaworld.co.kr/69">참고 : AWS의 mysql db 접속
